version: "3.8"

services:
  backend:
    container_name: backend_service
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mongo
      - redis
    restart: always
    networks:
      - app-network

  frontend:
    container_name: frontend_service
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
